/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: 01628482de78d5d211ab350d70d8c4ca)
interface __BaseEnv_CloudflareBindings {
	SUPABASE_URL: "https://bfbaqyhyxergcpsyhzcc.supabase.co";
	PUBLIC_API_URL: "https://api.getkindl.ing";
	GEMINI_API_KEY: string;
	OPENAI_API_KEY: string;
	SUPABASE_API_KEY: string;
	GOOGLE_MAPS_API_KEY: string;
	POSTHOG_PROJECT_TOKEN: string;
	POSTHOG_HOST: string;
	ENVIRONMENT: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL" | "PUBLIC_API_URL" | "GEMINI_API_KEY" | "OPENAI_API_KEY" | "SUPABASE_API_KEY" | "GOOGLE_MAPS_API_KEY" | "POSTHOG_PROJECT_TOKEN" | "POSTHOG_HOST" | "ENVIRONMENT">> {}
}
