/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: 8dd5d30fe634ac74eefe1dcac6505f3d)
interface __BaseEnv_CloudflareBindings {
	SUPABASE_URL: "https://bfbaqyhyxergcpsyhzcc.supabase.co";
	PUBLIC_API_URL: "https://api.getkindl.ing";
	OPENAI_API_KEY: string;
	SUPABASE_API_KEY: string;
	GOOGLE_MAPS_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL" | "PUBLIC_API_URL" | "OPENAI_API_KEY" | "SUPABASE_API_KEY" | "GOOGLE_MAPS_API_KEY">> {}
}
