create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  source text not null check (source in ('web', 'ios')),
  name text not null check (char_length(btrim(name)) between 1 and 100),
  email text check (
    email is null or char_length(btrim(email)) between 3 and 254
  ),
  message text not null check (char_length(btrim(message)) between 1 and 4000),
  user_id uuid references auth.users (id) on delete set null,
  status text not null default 'new' check (status in ('new', 'in_progress', 'resolved', 'spam'))
);

create index if not exists contact_submissions_created_at_idx
  on public.contact_submissions (created_at desc);

alter table public.contact_submissions enable row level security;

drop policy if exists "Anyone can create contact submissions"
  on public.contact_submissions;

create policy "Anyone can create contact submissions"
  on public.contact_submissions
  for insert
  to anon, authenticated
  with check (
    source in ('web', 'ios')
    and (user_id is null or user_id = (select auth.uid()))
  );

revoke all on table public.contact_submissions from anon, authenticated;
grant insert on table public.contact_submissions to anon, authenticated;
