create table if not exists public.idea_shares (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users (id) on delete cascade,
  idea_id bigint not null references public.ideas (id) on delete cascade,
  unique (user_id, idea_id)
);

create index if not exists idea_shares_user_id_idx
  on public.idea_shares (user_id);

alter table public.idea_shares enable row level security;

drop policy if exists "Users can record their own idea shares"
  on public.idea_shares;

create policy "Users can record their own idea shares"
  on public.idea_shares
  for insert
  to authenticated
  with check (user_id = (select auth.uid()));

drop policy if exists "Users can read their own idea shares"
  on public.idea_shares;

create policy "Users can read their own idea shares"
  on public.idea_shares
  for select
  to authenticated
  using (user_id = (select auth.uid()));

grant select, insert on table public.idea_shares to authenticated;
grant usage on sequence public.idea_shares_id_seq to authenticated;
