create table if not exists public.idea_deletions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users (id) on delete cascade,
  idea_id bigint references public.ideas (id) on delete set null,
  local_id text not null
);

create index if not exists idea_deletions_user_id_idx
  on public.idea_deletions (user_id);

alter table public.idea_deletions enable row level security;

drop policy if exists "Users can record their own idea deletions"
  on public.idea_deletions;

create policy "Users can record their own idea deletions"
  on public.idea_deletions
  for insert
  to authenticated
  with check (user_id = (select auth.uid()));

drop policy if exists "Users can read their own idea deletions"
  on public.idea_deletions;

create policy "Users can read their own idea deletions"
  on public.idea_deletions
  for select
  to authenticated
  using (user_id = (select auth.uid()));

grant select, insert on table public.idea_deletions to authenticated;
grant usage on sequence public.idea_deletions_id_seq to authenticated;

-- Each public share open is attributed to the user who owns that idea in a
-- collection. The backend inserts these rows with its service key; users can
-- only read their own rows through RLS.
create table if not exists public.idea_share_opens (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  idea_id bigint not null references public.ideas (id) on delete cascade,
  owner_user_id uuid not null references auth.users (id) on delete cascade
);

create index if not exists idea_share_opens_owner_user_id_idx
  on public.idea_share_opens (owner_user_id);

create index if not exists idea_share_opens_idea_id_idx
  on public.idea_share_opens (idea_id);

alter table public.idea_share_opens enable row level security;

drop policy if exists "Users can read opens for their own ideas"
  on public.idea_share_opens;

create policy "Users can read opens for their own ideas"
  on public.idea_share_opens
  for select
  to authenticated
  using (owner_user_id = (select auth.uid()));

grant select on table public.idea_share_opens to authenticated;
